### ISSUE TITLE
Unable to see extra information in the log message.

### ISSUE THREAD

**Issue by symbolix** [keitheis/alog#14]
Hi,

I am trying to create a simple test case with your logger. However, when I do this:

```
import alog
alog.info("Hi.")
```

I should be getting this:

```
2016-08-18 20:44:30,208 INFO  <stdin> Hi.
```

Instead, I am getting this:

```
2016-11-02 15:13:56,942 INFO  [..app:2] Hi.
```

So I am not sure how to enable all the extra information such as `thread` and `process`.

Maybe this is due to lack of examples? Is it possible to add couple of examples? Thanks for the effort of putting this project together.

**Comment by symbolix** [comment]
Seems to be working now, not sure what went wrong. I did a fresh git clone and also started with a fresh python environment.

**Comment by symbolix** [comment]
However, still not sure why the example in the README and the actual result look different.

```
2016-08-18 20:45:19,372 INFO  <stdin:2> Test 1
```

I am not getting that `<stdin:2>` bit. Thanks.

**Comment by keitheis** [comment]
Hi @symbolix, **stdin** means the code is executed inside Python interactive shell instead of inside app.py. :)

**Comment by symbolix** [comment]
Cool! Thank you very much for the information.
